#!/bin/bash
#
# executable: delete
#
# Delete the Management BOSH Director
#
set -euo pipefail

##
# Set our current working directory to the root of the BcP repo
#
scriptAbsolutePath="$(dirname "$(readlink -f "$BASH_SOURCE")")"
cd "$scriptAbsolutePath"

##
# BcP Setup
# Validates the current setup and guides the user if deviations are found
#
. "bcp/.scripts/setup.sh"

##
# !! DEPLOYMENT METADATA !!
#    Must be filled out!
#
DEPLOYMENT_NAME="BcP-bosh"
DEPLOYMENT_DIRECTOR="BcP-bosh"

echo_deployment_metadata

##
# An array of external dependencies (clones) for this deployment.
# The array must contain the git repository URLs for the dependencies.
# Example:
#   "https://github.com/cloudfoundry/bosh-deployment.git"
#   "https://github.com/cloudfoundry/cf-deployment.git"
#
declare -a dependencies=(
    "https://github.com/cloudfoundry/bosh-deployment.git"
)

load_dependencies "${dependencies[@]}"

##
# Make sure we've selected the correct Director for this operation
#
check_deployment_and_selected_director

##
# BOSH Deployment Deletion Definition
#

bosh -e "$BcP_SELECTED_DIRECTOR" delete-env "bcp/clones/bosh-deployment/bosh.yml" \
    --state="state.json" \
    --vars-store="creds.yml" \
    -v director_name="$DEPLOYMENT_NAME" \
    -v internal_ip="172.16.174.180" \
    -v internal_gw="172.16.174.1" \
    -v internal_cidr="172.16.174.0/24" \
    -o "bcp/clones/bosh-deployment/vsphere/cpi.yml" \
        -v network_name="Puzzel_DS/VMNet 172.16.174.0" \
        -v vcenter_dc="DC" \
        -v vcenter_cluster="QA" \
        -v vcenter_ds="q1vmfs.+FC" \
        -v vcenter_ip="172.16.174.158" \
        -v vcenter_user="$(az keyvault secret show --vault-name "bosh-prod-uks-kv" --name "qaVcenterUser" --query "value" -o tsv)" \
        -v vcenter_password="$(az keyvault secret show --vault-name "bosh-prod-uks-kv" --name "qaVcenterPassword" --query "value" -o tsv)" \
        -v vcenter_templates="$DEPLOYMENT_NAME-templates" \
        -v vcenter_vms="$DEPLOYMENT_NAME-vms" \
        -v vcenter_disks="$DEPLOYMENT_NAME-disks" \
    -o "bcp/clones/bosh-deployment/misc/ntp.yml" \
        -v internal_ntp='["q1dc01.qa.local", "q1dc02.qa.local"]' \
    -o ops/add-azure-cpi.yml \
    -o "bcp/clones/bosh-deployment/uaa.yml" \
    -o "bcp/clones/bosh-deployment/credhub.yml" \
    -o "bcp/clones/bosh-deployment/jumpbox-user.yml" \
    -o "bcp/clones/bosh-deployment/misc/trusted-certs.yml" \
        --var-file trusted_ca_cert="bcp/blobs/puzzel-qa-ca-certs.pem" \
    -o "bcp/clones/bosh-deployment/misc/dns.yml" \
        -v internal_dns='["172.16.140.18", "172.16.140.20"]' \
    -o "bcp/common-ops/remove-dev-tools-from-vms.yml" \
    -o "bcp/common-ops/change-deployment-name.yml" \
        -v deployment_name="$DEPLOYMENT_NAME" \
    -o "bcp/common-ops/bosh-uaa-use-puzzel-ldap.yml" \
        -v ldap_server_urls="ldap://q1dc01.qa.local:389 ldap://q1dc01.qa.local:389" \
        -v ldap_bind_dn="$(az keyvault secret show --vault-name "bosh-prod-uks-kv" --name "ldap-bcp-sbx-bosh-bind-dn" --query "value" -o tsv)" \
        -v ldap_bind_password="$(az keyvault secret show --vault-name "bosh-prod-uks-kv" --name "ldap-bcp-sbx-bosh-bind-password" --query "value" -o tsv)" \
        -v ldap_search_base="OU=QALOCAL,DC=qa,DC=local" \
        -v ldap_group_search_base="OU=Groups,OU=QALOCAL,DC=qa,DC=local" \
    -o "ops/bosh-uaa-external-group-mappings.yml"

##
# Post-deployment activities
#
if [[ $? -eq 0 ]]; then

    # Delete 'creds.yml' and 'state.json' files from the external stores
    sync_creds_file_to_blob_store "$DEPLOYMENT_NAME" "delete"
    sync_state_file_to_git "$DEPLOYMENT_NAME" "delete"

    # Clean-up any remaining files
    rm "creds.yml" 2>/dev/null || true
    rm "state.json" 2>/dev/null || true
fi

##
# DEPLOYMENT OPERATION COMPLETED!
#
printf "\n\n"
bold_green_msg_nn "FINISHED "
bold_red_msg_nn "--DELETING--"
green_msg ": ${DEPLOYMENT_NAME}!"
printf "\n\n"