#!/bin/bash
#
# executable: deploy
#
# Deploy the bcp BOSH Director
#
set -euo pipefail

##
# Set our current working directory to the root of the bcp repo
#
scriptAbsolutePath="$(dirname "$(readlink -f "$BASH_SOURCE")")"
cd "$scriptAbsolutePath"

##
# bcp Setup
# Validates the current setup and guides the user if deviations are found
#
. "bcp/.scripts/setup.sh"

##
# !! DEPLOYMENT METADATA !!
#    Must be filled out!
#
DEPLOYMENT_NAME="bcp-sbx-bosh"
DEPLOYMENT_DIRECTOR="bcp-sbx-bosh"

echo_deployment_metadata

##
# An array of external dependencies (clones) for this deployment.
# The array must contain the git repository URLs for the dependencies.
# Example:
#   "https://github.com/cloudfoundry/bosh-deployment.git"
#   "https://github.com/cloudfoundry/cf-deployment.git"
#
declare -a dependencies=(
    "https://github.com/cloudfoundry/bosh-deployment.git"
)

load_dependencies "${dependencies[@]}"

##
# Check if the Director is already initialized.
#
check_if_target_director_is_initialized "$DEPLOYMENT_DIRECTOR" "true"

##
# BOSH Deployment Definition
#

bosh create-env "bcp/clones/bosh-deployment/bosh.yml" \
    --state="state.json" \
    --vars-store="creds.yml" \
    -v director_name="$DEPLOYMENT_NAME" \
    -v internal_ip="172.16.174.180" \
    -v internal_gw="172.16.174.1" \
    -v internal_cidr="172.16.174.0/24" \
    -o "bcp/clones/bosh-deployment/vsphere/cpi.yml" \
        -v network_name="Puzzel_DS/VMNet 172.16.174.0" \
        -v vcenter_dc="DC" \
        -v vcenter_cluster="QA" \
        -v vcenter_ds="q1vmfs.+NL" \
        -v vcenter_ip="172.16.174.158" \
        -v vcenter_user="$(az keyvault secret show --vault-name "bosh-prod-uks-kv" --name "qaVcenterUser" --query "value" -o tsv)" \
        -v vcenter_password="$(az keyvault secret show --vault-name "bosh-prod-uks-kv" --name "qaVcenterPassword" --query "value" -o tsv)" \
        -v vcenter_templates="$DEPLOYMENT_NAME-templates" \
        -v vcenter_vms="$DEPLOYMENT_NAME-vms" \
        -v vcenter_disks="$DEPLOYMENT_NAME-disks" \
    -o "bcp/clones/bosh-deployment/misc/ntp.yml" \
        -v internal_ntp='["d1dc01.dev.local", "d1dc02.dev.local", "d1dc03.dev.local"]' \
    -o "bcp/clones/bosh-deployment/uaa.yml" \
    -o "bcp/clones/bosh-deployment/credhub.yml" \
    -o "bcp/clones/bosh-deployment/jumpbox-user.yml" \
    -o "bcp/clones/bosh-deployment/misc/trusted-certs.yml" \
        --var-file trusted_ca_cert="bcp/blobs/puzzel-qa-ca-certs.pem" \
    -o "bcp/clones/bosh-deployment/misc/dns.yml" \
        -v internal_dns='["172.16.150.11", "172.16.150.12", "172.16.150.13"]' \
    -o "bcp/common-ops/remove-dev-tools-from-vms.yml" \
    -o "bcp/common-ops/change-deployment-name.yml" \
        -v deployment_name="$DEPLOYMENT_NAME" \
    -o "bcp/common-ops/bosh-uaa-use-puzzel-ldap.yml" \
        -v ldap_server_urls="ldap://d1dc01.dev.local:389 ldap://d1dc02.dev.local:389 ldap://d1dc03.dev.local:389" \
        -v ldap_bind_dn="$(az keyvault secret show --vault-name "bosh-prod-uks-kv" --name "ldap-$DEPLOYMENT_DIRECTOR-bind-dn" --query "value" -o tsv)" \
        -v ldap_bind_password="$(az keyvault secret show --vault-name "bosh-prod-uks-kv" --name "ldap-$DEPLOYMENT_DIRECTOR-bind-password" --query "value" -o tsv)" \
        -v ldap_search_base="OU=DEVLOCAL,DC=dev,DC=local" \
        -v ldap_group_search_base="OU=Groups,OU=DEVLOCAL,DC=dev,DC=local" \
    -o "ops/bosh-uaa-external-group-mappings.yml"

##
# Post-deployment activities
#
if [[ $? -eq 0 ]]; then

    # Set 'creds.yml' and 'state.json' file permissions
    chmod 600 "creds.yml"
    chmod 600 "state.json"

    # Sync 'creds.yml' and 'state.json' files to the external stores
    sync_creds_file_to_blob_store "$DEPLOYMENT_NAME" "sync"
    sync_state_file_to_git "$DEPLOYMENT_NAME" "sync"

    # Connect to the deployed BOSH Director
    connect_to_bosh "172.16.174.180"

    # Upload the Cloud Config to be used by all deployments made by this BOSH Director
    bosh -n update-cloud-config "cloud-config/$DEPLOYMENT_NAME/cloud-config.yml"

    # Ensure we have BOSH DNS available for all deployments made by this BOSH Director
    bosh -n update-runtime-config "bcp/clones/bosh-deployment/runtime-configs/dns.yml"

    # Upload Ubuntu Bionic stemcell
    bosh -n upload-stemcell --sha1 2a41d41780fac1837ad9d17cf56063dd06ab24cb \
        https://bosh.io/d/stemcells/bosh-vsphere-esxi-ubuntu-bionic-go_agent?v=1.107

fi

##
# DEPLOYMENT OPERATION COMPLETED!
#
printf "\n\n"
bold_green_msg_nn "FINISHED DEPLOYING: "
green_msg "${DEPLOYMENT_NAME}"
printf "\n\n"