name: bcp-sbx-core-services

releases:
- name: "minio"
  version: "2022-09-17T00-09-45Z"
  url: "https://bosh.io/d/github.com/minio/minio-boshrelease?v=2022-09-17T00-09-45Z"
  sha1: "98721a8523982b5f52c812ff60f079bd07a09f85"
- name: "uaa"
  version: "76.0.0"
  url: "https://bosh.io/d/github.com/cloudfoundry/uaa-release?v=76.0.0"
  sha1: "83bc6c978a2a64e53f8dcfe5838b994091995758"
- name: "credhub"
  version: "2.12.9"
  url: "https://bosh.io/d/github.com/pivotal-cf/credhub-release?v=2.12.9"
  sha1: "45985800a5cab506c84db53102649a1b36c8f2a0"
- name: "bpm"
  version: "1.1.19"
  url: "https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.19"
  sha1: "669baca975c6def518c7e736dbf189cfb438475b"

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

stemcells:
- alias: default
  os: ubuntu-bionic
  version: latest

features:
  use_dns_addresses: true
  randomize_az_placement: true

instance_groups:
- name: core-services
  instances: 4
  azs: [vsphere]
  networks:
    - name: vsphere-default
  vm_type: large
  stemcell: default
  persistent_disk: 50000
  jobs:
  - name: minio-server
    release: minio
    provides:
      minio-server: { as: blobstore, shared: true }
      blobstore-address: { as: blobstore-address }
    custom_provider_definitions:
    - name: blobstore-address
      type: address
    properties:
      credential:
        accesskey: ((minio_accesskey))
        secretkey: ((minio_secretkey))
      server_cert: ((blobstore_cert.certificate))
      server_key: ((blobstore_cert.private_key))
      ca_cert: ((blobstore_cert.ca))

  - name: uaa
    release: uaa
    properties:
      encryption:
        active_key_label: uaa-encryption-key-1
        encryption_keys:
        - label: uaa-encryption-key-1
          passphrase: ((uaa_encryption_key_1))
      login:
        saml:
          activeKeyId: uaa-saml-key-1
          keys:
            uaa-saml-key-1:
              certificate: ((uaa_service_provider_ssl.certificate))
              key: ((uaa_service_provider_ssl.private_key))
              passphrase: ""
      uaa:
        clients:
          admin:
            authorities: bosh.admin
            authorized-grant-types: client_credentials
            override: true
            scope: ""
            secret: ((admin_password))
          bosh_cli:
            access-token-validity: 120
            authorities: uaa.none
            authorized-grant-types: password,refresh_token
            override: true
            refresh-token-validity: 86400
            scope: openid,bosh.admin,bosh.read,bosh.*.admin,bosh.*.read,bosh.teams.*.admin,bosh.teams.*.read
            secret: ""
          hm:
            authorities: bosh.admin
            authorized-grant-types: client_credentials
            override: true
            scope: ""
            secret: ((hm_password))
          nats:
            authorities: bosh.admin
            authorized-grant-types: client_credentials
            override: true
            scope: ""
            secret: ((nats_sync_password))
          uaa_admin:
            authorities: uaa.admin
            authorized-grant-types: client_credentials
            override: true
            scope: ""
            secret: ((uaa_admin_client_secret))
          director_to_credhub:
            access-token-validity: 3600
            authorities: credhub.read,credhub.write
            authorized-grant-types: client_credentials
            override: true
            scope: ""
            secret: ((uaa_clients_director_to_credhub))
          credhub_cli:
            access-token-validity: 60
            authorities: ""
            authorized-grant-types: password,refresh_token
            override: true
            refresh-token-validity: 1800
            scope: credhub.read,credhub.write
            secret: ""
          credhub-admin:
            access-token-validity: 3600
            authorities: credhub.read,credhub.write
            authorized-grant-types: client_credentials
            override: true
            scope: ""
            secret: ((credhub_admin_client_secret))
        jwt:
          policy:
            active_key_id: uaa-jwt-key-1
            keys:
              uaa-jwt-key-1:
                signingKey: ((uaa_jwt_signing_key.private_key))
          revocable: true
        scim:
          groups:
            bosh.admin: User has admin access on any Director
            bosh.read: User has read access on any Director
            bosh.releases.upload: User can upload new releases
            bosh.stemcells.upload: User can upload new stemcells
          users:
          - name: admin
            password: ((admin_password))
            groups:
            - bosh.admin
          - name: credhub_cli_user
            password: ((credhub_cli_user_password))
            groups:
            - credhub.read
            - credhub.write
        ca_certs:
        - ((/bcp-sbx-bosh/bcp-sbx-core-database/mysql_server_certificate.ca))
        sslCertificate: ((uaa_ssl.certificate))
        sslPrivateKey: ((uaa_ssl.private_key))
        #url: https://((internal_ip)):8443
        url: "https://q-s3.core-services.vsphere-default.bcp-sbx-core-services.bosh:8443"
        zones:
          internal:
            hostnames:
            # - ((internal_ip))
            - "q-s3.core-services.vsphere-default.bcp-sbx-core-services.bosh"
            - "q-s0.core-services.vsphere-default.bcp-sbx-core-services.bosh"
            - "bosh-core-services.qa.local"
            #- "172.16.174.184"
      uaadb:
        address: "q-s3.mysql.vsphere-default.bcp-sbx-core-database.bosh"
        # address: "172.16.174.181"
        databases:
        - name: uaa
          tag: uaa
        db_scheme: mysql
        port: 3306
        roles:
        - name: uaa-db-user
          password: ((/bcp-sbx-bosh/bcp-sbx-core-database/uaa-db-pwd))
          tag: admin
        tls: enabled

  - name: bbr-uaadb
    release: uaa
    properties:
      release_level_backup: true
      uaadb:
        address: "q-s3.mysql.vsphere-default.bcp-sbx-core-database.bosh"
        #address: "172.16.174.181"
        ca_cert: ((/bcp-sbx-bosh/bcp-sbx-core-database/mysql_server_certificate.ca))
        databases:
        - name: uaa
          tag: uaa
        db_scheme: mysql
        port: 3306
        roles:
        - name: uaa-db-user
          password: ((/bcp-sbx-bosh/bcp-sbx-core-database/uaa-db-pwd))
          tag: admin
    
  - name: credhub
    release: credhub
    properties:
      credhub:
        authentication:
          uaa:
            ca_certs:
            - ((uaa_ssl.ca))
            # url: "https://q-s0.core-services.vsphere-default.bcp-sbx-core-services.bosh:8443"
            # url: "https://172.16.174.184:8443"
            url: "https://bosh-core-services.qa.local:8443"
            verification_key: ((uaa_jwt_signing_key.public_key))
        authorization:
          acls:
            enabled: false
        certificates:
          concatenate_cas: true
        data_storage:
          database: credhub
          host: "q-s3.mysql.vsphere-default.bcp-sbx-core-database.bosh"
          password: ((/bcp-sbx-bosh/bcp-sbx-core-database/credhub-db-pwd))
          port: 3306
          require_tls: true
          tls_ca: ((/bcp-sbx-bosh/bcp-sbx-core-database/mysql_server_certificate.ca))
          type: mysql
          username: credhub-db-user
        encryption:
          keys:
          - active: true
            key_properties:
              encryption_password: ((credhub_encryption_password))
            provider_name: internal
          providers:
          - name: internal
            type: internal
        tls: ((credhub_tls))

  - name: bbr-credhubdb
    release: credhub
    properties:
      credhub:
        data_storage:
          database: credhub
          host: "q-s3.mysql.vsphere-default.bcp-sbx-core-database.bosh"
          password: ((/bcp-sbx-bosh/bcp-sbx-core-database/credhub-db-pwd))
          port: 3306
          require_tls: true
          tls_ca: ((/bcp-sbx-bosh/bcp-sbx-core-database/mysql_server_certificate.ca))
          type: mysql
          username: credhub-db-user
      release_level_backup: true

update:
  canaries: 1
  canary_watch_time: 10000-600000
  max_in_flight: 1
  update_watch_time: 10000-600000

variables:
# Variables for Minio and common core services ca
- name: minio_accesskey
  type: password

- name: minio_secretkey
  type: password

- name: core_services_ca
  type: certificate
  options:
    is_ca: true
    common_name: Core Services CA
    # common_name: BCP Core Blobstore CA

- name: blobstore_cert
  type: certificate
  options:
    ca: core_services_ca
    common_name: BCP Core Blobstore
  consumes:
    alternative_name:
      from: blobstore-address
      properties: { wildcard: true }

# Variables for UAA
- name: uaa_jwt_signing_key
  type: rsa

- name: uaa_admin_client_secret
  type: password

- name: uaa_encryption_key_1
  type: password

- name: admin_password
  type: password

- name: hm_password
  type: password

- name: nats_sync_password
  type: password

- name: uaa_ssl
  options:
    alternative_names:
    - q-s3.core-services.vsphere-default.bcp-sbx-core-services.bosh
    - "*.core-services.vsphere-default.bcp-sbx-core-services.bosh"
    # - "172.16.174.184"
    - "bosh-core-services.qa.local"
    ca: core_services_ca
    common_name: q-s3.core-services.vsphere-default.bcp-sbx-core-services.bosh
  type: certificate

- name: uaa_service_provider_ssl
  options:
    alternative_names:
    - q-s3.core-services.vsphere-default.bcp-sbx-core-services.bosh
    - "*.core-services.vsphere-default.bcp-sbx-core-services.bosh"
    - "bosh-core-services.qa.local"
    ca: core_services_ca
    common_name: q-s3.core-services.vsphere-default.bcp-sbx-core-services.bosh
  type: certificate

# Variables for Credhub
- name: credhub_tls
  options:
    alternative_names:
    - q-s3.core-services.vsphere-default.bcp-sbx-core-services.bosh
    - "*.core-services.vsphere-default.bcp-sbx-core-services.bosh"
    - "bosh-core-services.qa.local"
    ca: core_services_ca
    common_name: q-s3.core-services.vsphere-default.bcp-sbx-core-services.bosh
  type: certificate

- name: credhub_cli_user_password
  type: password

- name: credhub_encryption_password
  type: password

- name: uaa_clients_director_to_credhub
  type: password

- name: credhub_admin_client_secret
  type: password