name: bcp-sbx-core-services

releases:
- name: "minio"
  version: "2022-09-17T00-09-45Z"
  url: "https://bosh.io/d/github.com/minio/minio-boshrelease?v=2022-09-17T00-09-45Z"
  sha1: "98721a8523982b5f52c812ff60f079bd07a09f85"
- name: "uaa"
  version: "76.0.0"
  url: "https://bosh.io/d/github.com/cloudfoundry/uaa-release?v=76.0.0"
  sha1: "83bc6c978a2a64e53f8dcfe5838b994091995758"
# - name: uaa
#   sha1: 0cfe2ec783c9ad1de861d873f9c5e6cfb920f675
#   url: https://s3.amazonaws.com/bosh-compiled-release-tarballs/uaa-76.0.0-ubuntu-jammy-1.18-20220921-141451-277777927-20220921141454.tgz
#   version: 76.0.0
# I think this one is just already compiled, to easier keep track of latest release throug bosh.io/releases, use the othe uncommented one.

stemcells:
- alias: default
  os: ubuntu-bionic
  version: latest

features:
  use_dns_addresses: true
  randomize_az_placement: true

instance_groups:
- name: core-services
  # name: minio
  instances: 4
  azs: [vsphere]
  networks:
    - name: vsphere-default
  vm_type: large
  stemcell: default
  persistent_disk: 50000
  jobs:
  - name: minio-server
    release: minio
    provides:
      minio-server: { as: blobstore, shared: true }
      blobstore-address: { as: blobstore-address }
    custom_provider_definitions:
    - name: blobstore-address
      type: address
    properties:
      credential:
        accesskey: ((minio_accesskey))
        secretkey: ((minio_secretkey))
      server_cert: ((blobstore_cert.certificate))
      server_key: ((blobstore_cert.private_key))
      ca_cert: ((blobstore_cert.ca))

  - name: uaa
    release: uaa
    properties:
      encryption:
        active_key_label: uaa-encryption-key-1
        encryption_keys:
        - label: uaa-encryption-key-1
          passphrase: ((uaa_encryption_key_1))
      login:
        saml:
          activeKeyId: uaa-saml-key-1
          keys:
            uaa-saml-key-1:
              certificate: ((uaa_service_provider_ssl.certificate))
              key: ((uaa_service_provider_ssl.private_key))
              passphrase: ""
      uaa:
        clients:
          admin:
            authorities: bosh.admin
            authorized-grant-types: client_credentials
            override: true
            scope: ""
            secret: ((admin_password))
          bosh_cli:
            access-token-validity: 120
            authorities: uaa.none
            authorized-grant-types: password,refresh_token
            override: true
            refresh-token-validity: 86400
            scope: openid,bosh.admin,bosh.read,bosh.*.admin,bosh.*.read,bosh.teams.*.admin,bosh.teams.*.read
            secret: ""
          hm:
            authorities: bosh.admin
            authorized-grant-types: client_credentials
            override: true
            scope: ""
            secret: ((hm_password))
          nats:
            authorities: bosh.admin
            authorized-grant-types: client_credentials
            override: true
            scope: ""
            secret: ((nats_sync_password))
          uaa_admin:
            authorities: uaa.admin
            authorized-grant-types: client_credentials
            override: true
            scope: ""
            secret: ((uaa_admin_client_secret))
        jwt:
          policy:
            active_key_id: uaa-jwt-key-1
            keys:
              uaa-jwt-key-1:
                signingKey: ((uaa_jwt_signing_key.private_key))
        scim:
          groups:
            bosh.admin: User has admin access on any Director
            bosh.read: User has read access on any Director
            bosh.releases.upload: User can upload new releases
            bosh.stemcells.upload: User can upload new stemcells
          users:
          - groups:
            - bosh.admin
            name: admin
            password: ((admin_password))
        sslCertificate: ((uaa_ssl.certificate))
        sslPrivateKey: ((uaa_ssl.private_key))
        url: https://((internal_ip)):8443
        zones:
          internal:
            hostnames:
            - ((internal_ip))
      uaadb:
        address: 127.0.0.1
        databases:
        - name: uaa
          tag: uaa
        db_scheme: postgresql
        port: 5432
        roles:
        - name: postgres
          password: ((postgres_password))
          tag: admin
        tls: disabled

update:
  canaries: 1
  canary_watch_time: 10000-600000
  max_in_flight: 1
  update_watch_time: 10000-600000

variables:
- name: minio_accesskey
  type: password

- name: minio_secretkey
  type: password

- name: blobstore_ca
  type: certificate
  options:
    is_ca: true
    common_name: BCP Core Blobstore CA

- name: blobstore_cert
  type: certificate
  options:
    ca: blobstore_ca
    common_name: BCP Core Blobstore
  consumes:
    alternative_name:
      from: blobstore-address
      properties: { wildcard: true }