name: bcp-sbx-core-database

releases:
- name: "pxc"
  version: "0.45.0"
  url: "https://bosh.io/d/github.com/cloudfoundry-incubator/pxc-release?v=0.45.0"
  sha1: "8d45e8984685dddf1d4a007dc5172891646f8fe1"

- name: "bpm"
  version: "1.1.19"
  url: "https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.19"
  sha1: "669baca975c6def518c7e736dbf189cfb438475b"


addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

stemcells:
- alias: default
  os: ubuntu-bionic
  version: latest

features:
  use_dns_addresses: true
  use_short_dns_addresses: true
  randomize_az_placement: true

instance_groups:
- name: mysql
  instances: 3
  azs: [vsphere]
  networks:
  - name: vsphere-default
  vm_type: large
  stemcell: default
  persistent_disk: 30000
  jobs:
  - name: pxc-mysql
    release: pxc
    properties:
      port: 6033
      admin_password: ((admin_password))
      remote_admin_access: true
      tls:
        required: true
        galera: ((galera_server_certificate))
        server: ((mysql_server_certificate))
        # client:
        #   ca: ((/bcp-sbx-bosh/dev-bosh/director_ssl.ca))
      engine_config:
        galera:
          enabled: true
      seeded_users:
        galera-agent:
          password: ((galera_healthcheck_db_password))
          host: loopback
          role: minimal
        cluster-health-logger:
          password: ((cluster_health_password))
          host: loopback
          role: minimal

  - name: proxy
    release: pxc
    provides:
      proxy: { as: proxy, shared: true }
    properties:
      api_password: ((proxy_api_password))

  - name: galera-agent
    release: pxc
    properties:
      endpoint_password: ((galera_healthcheck_endpoint_password))
      db_password: ((galera_healthcheck_db_password))

  - name: cluster-health-logger
    release: pxc
    properties:
      db_password: ((cluster_health_password))

  - name: gra-log-purger
    release: pxc

  - name: bootstrap
    release: pxc

  - name: smoke-tests
    release: pxc
    properties:
      db_password: ((smoke_tests_db_password))

  - name: smoke-tests-user
    release: pxc

update:
  canaries: 1
  canary_watch_time: 10000-600000
  max_in_flight: 1
  update_watch_time: 10000-600000

variables:
- name: admin_password
  type: password

- name: cluster_health_password
  type: password

- name: galera_healthcheck_db_password
  type: password

- name: galera_healthcheck_endpoint_password
  type: password

- name: proxy_api_password
  type: password

- name: smoke_tests_db_password
  type: password

- name: pxc_galera_ca
  type: certificate
  options:
    is_ca: true
    common_name: pxc_galera_ca

- name: pxc_server_ca
  type: certificate
  options:
    is_ca: true
    common_name: pxc_server_ca

- name: galera_server_certificate
  type: certificate
  options:
    alternative_names:
    - "*.mysql.vsphere-default.bcp-sbx-core-database.bosh"
    ca: pxc_galera_ca
    extended_key_usage: [ "server_auth", "client_auth" ]
    common_name: galera_server_certificate

- name: mysql_server_certificate
  type: certificate
  options:
    alternative_names:
    - "*.mysql.vsphere-default.bcp-sbx-core-database.bosh"
    ca: pxc_server_ca
    common_name: mysql_server_certificate