#!/bin/bash
#
# executable: deployments/bcp-sbx-core-services/deploy
#
# Deploy the bcp Core Services
#
set -euo pipefail

##
# Set our current working directory to the root of the bcp repo
#
scriptAbsolutePath="$(dirname "$(readlink -f "$BASH_SOURCE")")"
cd "$scriptAbsolutePath/../../"

##
# bcp Setup
# Validates the current setup and guides the user if deviations are found
#
. "bcp/.scripts/setup.sh"

##
# !! DEPLOYMENT METADATA !!
#    Must be filled out!
#
DEPLOYMENT_NAME="bcp-sbx-core-services"
DEPLOYMENT_DIRECTOR="bcp-sbx-bosh"

echo_deployment_metadata

##
# An array of external dependencies (clones) for this deployment.
# The array must contain the git repository URLs for the dependencies.
# Example:
#   "https://github.com/cloudfoundry/bosh-deployment.git"
#   "https://github.com/cloudfoundry/cf-deployment.git"
#
declare -a dependencies=()

load_dependencies ${dependencies[@]+"${dependencies[@]}"}

##
# Make sure we're targeting the correct Director for this operation
#
check_deployment_and_selected_director

##
# BOSH Deployment Definition: bcp core services - blobstore
# use -n before -e if you do not wish to require user acceptance after it has been listed what will actually be deployed
bosh -e "$DEPLOYMENT_DIRECTOR" -d "${DEPLOYMENT_NAME}" \
    deploy --no-redact "deployments/$DEPLOYMENT_NAME/manifests/core-services.yml" \
    -v internal_ip="127.0.0.1" \
    -o "deployments/$DEPLOYMENT_NAME/ops/bosh-uaa-use-puzzel-ldap.yml" \
        -v ldap_server_urls="ldap://q1dc01.qa.local:389 ldap://q1dc01.qa.local:389" \
        -v ldap_bind_dn="$(az keyvault secret show --vault-name "bosh-prod-uks-kv" --name "ldap-$DEPLOYMENT_DIRECTOR-bind-dn" --query "value" -o tsv)" \
        -v ldap_bind_password="$(az keyvault secret show --vault-name "bosh-prod-uks-kv" --name "ldap-$DEPLOYMENT_DIRECTOR-bind-password" --query "value" -o tsv)" \
        -v ldap_search_base="OU=QALOCAL,DC=qa,DC=local" \
        -v ldap_group_search_base="OU=Groups,OU=QALOCAL,DC=qa,DC=local" \
    -o "deployments/$DEPLOYMENT_NAME/ops/bosh-uaa-external-group-mappings.yml"

##
# Post-deployment activities
#
if [[ $? -eq 0 ]]; then
    #
    # No activities specified
    #
    echo ""
fi

##
# DEPLOYMENT OPERATION COMPLETED!
#
printf "\n\n"
bold_green_msg_nn "FINISHED DEPLOYING: "
green_msg "${DEPLOYMENT_NAME}!"
printf "\n\n"