---
azs:
  - name: z1
    cloud_properties:
      datacenters:
        - name: CAP-ppp
          clusters:
            - nnn-Hybrid-OSL-MGMT-C01:
                host_group:
                  name: OSL3-Hosts
                  drs_rule: MUST

  - name: z2
    cloud_properties:
      datacenters:
        - name: CAP-ppp
          clusters:
            - nnn-Hybrid-OSL-MGMT-C01:
                host_group:
                  name: OSL5-Hosts
                  drs_rule: MUST

  - name: dual
    cloud_properties:
      datacenters:
        - name: CAP-ppp
          clusters:
            - nnn-Hybrid-OSL-MGMT-C01

compilation:
  workers: 4
  reuse_compilation_vms: true
  az: z1
  vm_type: large.mem
  network: default

disk_types:
#{{{ Single Disks
- name: 2GB
  disk_size: 2048
  cloud_properties:
    datastores: &single-mgmt-ds
    - "nnn-mgmt-std-single-osl3-3par05-L01"
    - "nnn-mgmt-std-single-osl5-3par06-L01"
    - "nnn-mgmt-std-single-osl3-3par05-L02"
    - "nnn-mgmt-std-single-osl5-3par06-L02"
    - "nnn-mgmt-std-single-osl3-3par07-L00"
    - "nnn-mgmt-std-single-osl5-3par06-L03"
- name: 5GB
  disk_size: 5120
  cloud_properties:
    datastores: *single-mgmt-ds
- name: 10GB
  disk_size: 10240
  cloud_properties:
    datastores: *single-mgmt-ds
- name: 50GB
  disk_size: 51200
  cloud_properties:
    datastores: *single-mgmt-ds
- name: 100GB
  disk_size: 100240
  cloud_properties:
    datastores: *single-mgmt-ds
- name: 200GB
  disk_size: 204800
  cloud_properties:
    datastores: *single-mgmt-ds
#}}}

#{{{ Dual Disks
- name: 2GB_dual
  disk_size: 2048
  cloud_properties:
    datastores: &dual-mgmt-ds
    - "nnn-mgmt-std-dual-osl3-3par05-L00"
- name: 5GB_dual
  disk_size: 5120
  cloud_properties:
    datastores: *dual-mgmt-ds
- name: 10GB_dual
  disk_size: 10240
  cloud_properties:
    datastores: *dual-mgmt-ds
- name: 50GB_dual
  disk_size: 51200
  cloud_properties:
    datastores: *dual-mgmt-ds
- name: 100GB_dual
  disk_size: 100240
  cloud_properties:
    datastores: *dual-mgmt-ds
- name: 200GB_dual
  disk_size: 204800
  cloud_properties:
    datastores: *dual-mgmt-ds
#}}}

networks:
  - name: default
    type: manual
    subnets:
      - range: "10.64.159.0/26"
        gateway: "10.64.159.1"
        dns:
        - "10.64.161.68"
        - "10.64.161.69"
        azs: [z1, z2, dual]
        reserved:
          # Range available to Director in IPAM: 10.64.159.5 - 10.64.159.61
          - "10.64.159.1-10.64.159.3"
          - "10.64.159.62"
        cloud_properties:
          name: nnn-BcP-core-sz.nnn1.osl.zzz.net

vm_extensions:
- name: single_site_disks
  cloud_properties:
    datastores: *single-mgmt-ds
- name: dual_site_disks
  cloud_properties:
    datastores: *dual-mgmt-ds
- name: cf-router-network-properties
- name: cf-tcp-router-network-properties
- name: diego-ssh-proxy-network-properties
- name: 50GB_ephemeral_disk
  cloud_properties:
    disk: 51200
- name: 100GB_ephemeral_disk
  cloud_properties:
    disk: 102400

vm_types:
#{{{ Nano
- name: nano
  cloud_properties:
    cpu: 1
    ram: 512
    disk: 8192
#}}}

#{{{ Micro Series
- name: micro
  cloud_properties:
    cpu: 1
    ram: 1024
    disk: 8192
- name: micro.cpu
  cloud_properties:
    cpu: 2
    ram: 1024
    disk: 8192
- name: micro.mem
  cloud_properties:
    cpu: 1
    ram: 2048
    disk: 8192
- name: micro.disk
  cloud_properties:
    cpu: 1
    ram: 1024
    disk: 16384
- name: micro.xldisk
  cloud_properties:
    cpu: 1
    ram: 1024
    disk: 32768
#}}}

#{{{ Small Series
- name: small
  cloud_properties:
    cpu: 2
    ram: 2048
    disk: 8192
- name: small.cpu
  cloud_properties:
    cpu: 4
    ram: 2048
    disk: 8192
- name: small.mem
  cloud_properties:
    cpu: 2
    ram: 4096
    disk: 8192
- name: small.disk
  cloud_properties:
    cpu: 2
    ram: 2048
    disk: 16384
- name: small.xldisk
  cloud_properties:
    cpu: 2
    disk: 32768
    ram: 2048
#}}}

#{{{ Medium Series
- name: medium
  cloud_properties:
    cpu: 4
    ram: 4096
    disk: 8192
- name: medium.cpu
  cloud_properties:
    cpu: 6
    ram: 4096
    disk: 8192
- name: medium.mem
  cloud_properties:
    cpu: 4
    ram: 8192
    disk: 8192
- name: medium.disk
  cloud_properties:
    cpu: 4
    ram: 4096
    disk: 32768
- name: medium.xldisk
  cloud_properties:
    cpu: 4
    ram: 4096
    disk: 65536
#}}}

#{{{ Large Series
- name: large
  cloud_properties:
    cpu: 6
    ram: 8192
    disk: 16384
- name: large.compute
  cloud_properties:
    cpu: 6
    ram: 8192
    disk: 8192
- name: large.cpu
  cloud_properties:
    cpu: 8
    ram: 8192
    disk: 16384
- name: large.mem
  cloud_properties:
    cpu: 6
    ram: 16384
    disk: 16384
- name: large.disk
  cloud_properties:
    cpu: 6
    ram: 8192
    disk: 65536
- name: large.xldisk
  cloud_properties:
    cpu: 6
    ram: 8192
    disk: 131072
#}}}

#{{{ X-Large Series
- name: xlarge
  cloud_properties:
    cpu: 8
    ram: 16384
    disk: 32768
- name: xlarge.compute
  cloud_properties:
    cpu: 8
    ram: 16384
    disk: 16384
- name: xlarge.cpu
  cloud_properties:
    cpu: 12
    ram: 8192
    disk: 32768
- name: xlarge.mem
  cloud_properties:
    cpu: 8
    ram: 32768
    disk: 32768
- name: xlarge.disk
  cloud_properties:
    cpu: 6
    ram: 16384
    disk: 131072
- name: xlarge.xldisk
  cloud_properties:
    cpu: 6
    ram: 16384
    disk: 262144
#}}}

#{{{ 2X-Large Series
- name: 2xlarge
  cloud_properties:
    cpu: 12
    ram: 32768
    disk: 65536
- name: 2xlarge.compute
  cloud_properties:
    cpu: 12
    ram: 32768
    disk: 32798
- name: 2xlarge.cpu
  cloud_properties:
    cpu: 16
    ram: 32768
    disk: 65536
- name: 2xlarge.mem
  cloud_properties:
    cpu: 12
    ram: 65536
    disk: 65536
- name: 2xlarge.disk
  cloud_properties:
    cpu: 12
    ram: 32768
    disk: 262144
- name: 2xlarge.xldisk
  cloud_properties:
    cpu: 12
    ram: 32768
    disk: 524288
#}}}

# vim: foldmethod=marker