azs:
- name: vsphere

networks:
- name: vsphere-default
  type: manual
  subnets:
  - azs:
    - vsphere
    cloud_properties:
      name: Puzzel_DS/VMNet 172.16.174.0
    dns:
    - 172.16.140.18
    - 172.16.140.20
    gateway: 172.16.174.1
    range: 172.16.174.0/24
    reserved:
    - 172.16.174.1-172.16.174.180
    - 172.16.174.195-172.16.174.255
    static:
    - 172.16.174.190-172.16.174.192
    - 172.16.174.184-172.16.174.187

vm_types:
  - name: small
    cloud_properties:
      cpu: 1
      ram: 1024
      disk: 10240
  - name: small.cpu
    cloud_properties:
      cpu: 2
      ram: 1024
      disk: 10240
  - name: small.ram
    cloud_properties:
      cpu: 1
      ram: 2048
      disk: 10240
  - name: small.disk
    cloud_properties:
      cpu: 1
      ram: 1024
      disk: 20480
  - name: medium
    cloud_properties:
      cpu: 2
      ram: 2048
      disk: 20480
  - name: medium.cpu
    cloud_properties:
      cpu: 4
      ram: 2048
      disk: 20480
  - name: medium.ram
    cloud_properties:
      cpu: 2
      ram: 4096
      disk: 20480
  - name: medium.disk
    cloud_properties:
      cpu: 2
      ram: 2048
      disk: 40960
  - name: large
    cloud_properties:
      cpu: 4
      ram: 4096
      disk: 40960
  - name: large.cpu
    cloud_properties:
      cpu: 6
      ram: 4096
      disk: 40960
  - name: large.ram
    cloud_properties:
      cpu: 4
      ram: 6144
      disk: 40960
  - name: large.disk
    cloud_properties:
      cpu: 4
      ram: 4096
      disk: 81920

compilation:
  reuse_compilation_vms: true
  az: vsphere
  network: vsphere-default
  vm_type: large
  workers: 3