azs:
- name: vsphere
  cpi: vsphere

- name: azure-euw-dev
  cpi: azure-euw-dev

- name: azure-uks-qa-1
  cpi: azure-uks-qa
  cloud_properties:
    availability_zone: "1"

- name: azure-uks-qa-2
  cpi: azure-uks-qa
  cloud_properties:
    availability_zone: "2"

- name: azure-uks-qa-3
  cpi: azure-uks-qa
  cloud_properties:
    availability_zone: "3"

networks:
- name: vsphere-default
  type: manual
  subnets:
  - azs:
    - vsphere
    cloud_properties:
      name: Puzzel_DS/VMNet 172.16.174.0
    dns:
    - 172.16.140.18
    - 172.16.140.20
    gateway: 172.16.174.1
    range: 172.16.174.0/24
    reserved:
    - 172.16.174.1-172.16.174.221
    - 172.16.174.230-172.16.174.255

- name: azure-euw-dev-default
  type: manual
  subnets:
  - azs:
    - azure-euw-dev
    cloud_properties:
      resource_group_name: network-dev-euw-rg
      virtual_network_name: testing-dev-euw-vnet
      subnet_name: testing-subnet
    dns:
    - 10.5.184.14
    gateway: 10.5.200.1
    range: 10.5.200.0/24
    reserved:
    - 10.5.200.1-10.5.200.199
    - 10.5.200.250-10.5.200.255

- name: azure-uks-qa-stag-app
  type: manual
  subnets:
  - azs:
    - azure-uks-qa-1
    - azure-uks-qa-2
    - azure-uks-qa-3
    cloud_properties:
      resource_group_name: network-stag-uks-rg
      virtual_network_name: appintnet-stag-uks-vnet
      subnet_name: appsubnet01
    dns:
    - 172.16.140.18
    - 172.16.140.20
    gateway: 10.7.179.1
    range: 10.7.179.0/27
    reserved:
    - 10.7.179.2-10.7.179.3

- name: azure-uks-qa-stag-endpoint
  type: manual
  subnets:
  - azs:
    - azure-uks-qa-1
    - azure-uks-qa-2
    - azure-uks-qa-3
    cloud_properties:
      resource_group_name: network-stag-uks-rg
      virtual_network_name: appintnet-stag-uks-vnet
      subnet_name: endpointsubnet01
    dns:
    - 172.16.140.18
    - 172.16.140.20
    gateway: 10.7.179.33
    range: 10.7.179.32/27
    reserved:
    - 10.7.179.34-10.7.179.35

- name: azure-uks-qa-stag-backend
  type: manual
  subnets:
  - azs:
    - azure-uks-qa-1
    - azure-uks-qa-2
    - azure-uks-qa-3
    cloud_properties:
      resource_group_name: network-stag-uks-rg
      virtual_network_name: backendsnet-stag-uks-vnet
      subnet_name: backends-subnet
    dns:
    - 172.16.140.18
    - 172.16.140.20
    gateway: 10.7.180.1
    range: 10.7.180.0/25
    reserved:
    - 10.7.180.2-10.7.180.3

- name: azure-uks-qa-stag-tm
  type: manual
  subnets:
  - azs:
    - azure-uks-qa-1
    - azure-uks-qa-2
    - azure-uks-qa-3
    cloud_properties:
      resource_group_name: network-stag-uks-rg
      virtual_network_name: backendsnet-stag-uks-vnet
      subnet_name: tm-subnet
    dns:
    - 172.16.140.18
    - 172.16.140.20
    gateway: 10.7.180.129
    range: 10.7.180.128/26
    reserved:
    - 10.7.180.130-10.7.180.131

- name: azure-uks-qa-stag-dmz-admin
  type: manual
  subnets:
  - azs:
    - azure-uks-qa-1
    - azure-uks-qa-2
    - azure-uks-qa-3
    cloud_properties:
      resource_group_name: network-stag-uks-rg
      virtual_network_name: dmznet-stag-uks-vnet
      subnet_name: dmz-subnet
    dns:
    - 172.16.140.18
    - 172.16.140.20
    gateway: 10.7.181.129
    range: 10.7.181.128/25
    reserved:
    - 10.7.181.130-10.7.181.131
    - 10.7.181.141-10.7.181.255

- name: azure-uks-qa-stag-dmz-agent
  type: manual
  subnets:
  - azs:
    - azure-uks-qa-1
    - azure-uks-qa-2
    - azure-uks-qa-3
    cloud_properties:
      resource_group_name: network-stag-uks-rg
      virtual_network_name: dmznet-stag-uks-vnet
      subnet_name: dmz-subnet
    dns:
    - 172.16.140.18
    - 172.16.140.20
    gateway: 10.7.181.129
    range: 10.7.181.128/25
    reserved:
    - 10.7.181.130-10.7.181.140
    - 10.7.181.152-10.7.181.255

- name: azure-uks-qa-stag-dmz-trigger
  type: manual
  subnets:
  - azs:
    - azure-uks-qa-1
    - azure-uks-qa-2
    - azure-uks-qa-3
    cloud_properties:
      resource_group_name: network-stag-uks-rg
      virtual_network_name: dmznet-stag-uks-vnet
      subnet_name: dmz-subnet
    dns:
    - 172.16.140.18
    - 172.16.140.20
    gateway: 10.7.181.129
    range: 10.7.181.128/25
    reserved:
    - 10.7.181.130-10.7.181.151
    - 10.7.181.163-10.7.181.255

- name: azure-uks-qa-stag-dmz-sms
  type: manual
  subnets:
  - azs:
    - azure-uks-qa-1
    - azure-uks-qa-2
    - azure-uks-qa-3
    cloud_properties:
      resource_group_name: network-stag-uks-rg
      virtual_network_name: dmznet-stag-uks-vnet
      subnet_name: dmz-subnet
    dns:
    - 172.16.140.18
    - 172.16.140.20
    gateway: 10.7.181.129
    range: 10.7.181.128/25
    reserved:
    - 10.7.181.130-10.7.181.162
    - 10.7.181.174-10.7.181.255

- name: azure-uks-qa-stag-dmz-ftp
  type: manual
  subnets:
  - azs:
    - azure-uks-qa-1
    - azure-uks-qa-2
    - azure-uks-qa-3
    cloud_properties:
      resource_group_name: network-stag-uks-rg
      virtual_network_name: dmznet-stag-uks-vnet
      subnet_name: dmz-subnet
    dns:
    - 172.16.140.18
    - 172.16.140.20
    gateway: 10.7.181.129
    range: 10.7.181.128/25
    reserved:
    - 10.7.181.130-10.7.181.173
    - 10.7.181.185-10.7.181.255

- name: azure-uks-qa-stag-mshare
  type: manual
  subnets:
  - azs:
    - azure-uks-qa-1
    - azure-uks-qa-2
    - azure-uks-qa-3
    cloud_properties:
      resource_group_name: network-stag-uks-rg
      virtual_network_name: msharenet-stag-uks-vnet
      subnet_name: msharenet-subnet
    dns:
    - 172.16.140.18
    - 172.16.140.20
    gateway: 10.7.177.1
    range: 10.7.177.0/26
    reserved:
    - 10.7.177.2-10.7.177.3

vm_types:
  - name: small
    cloud_properties:
      cpu: 1
      ram: 1024
      disk: 10240
      instance_type: Standard_A1_v2
      root_disk:
        size: 5120
      ephemeral_disk:
        use_root_disk: false
        size: 30720
  - name: small.cpu
    cloud_properties:
      cpu: 2
      ram: 1024
      disk: 10240
      instance_type: Standard_A2_v2
      root_disk:
        size: 5120
      ephemeral_disk:
        use_root_disk: false
        size: 30720
  - name: small.ram
    cloud_properties:
      cpu: 1
      ram: 2048
      disk: 10240
      instance_type: Standard_A1_v2
      root_disk:
        size: 5120
      ephemeral_disk:
        use_root_disk: false
        size: 30720
  - name: small.disk
    cloud_properties:
      cpu: 1
      ram: 1024
      disk: 20480
  - name: medium
    cloud_properties:
      cpu: 2
      ram: 2048
      disk: 20480
      instance_type: Standard_D2s_v5
      root_disk:
        size: 5120
      ephemeral_disk:
        use_root_disk: false
        size: 30720
  - name: medium.cpu
    cloud_properties:
      cpu: 4
      ram: 2048
      disk: 20480
      instance_type: Standard_D4s_v5
      root_disk:
        size: 5120
      ephemeral_disk:
        use_root_disk: false
        size: 30720
  - name: medium.ram
    cloud_properties:
      cpu: 2
      ram: 4096
      disk: 20480
  - name: medium.disk
    cloud_properties:
      cpu: 2
      ram: 2048
      disk: 40960
  - name: large
    cloud_properties:
      cpu: 4
      ram: 4096
      disk: 40960
      instance_type: Standard_D4s_v5
      root_disk:
        size: 5120
      ephemeral_disk:
        use_root_disk: false
        size: 30720
  - name: large.cpu
    cloud_properties:
      cpu: 6
      ram: 4096
      disk: 40960
      instance_type: Standard_D8s_v5
      root_disk:
        size: 5120
      ephemeral_disk:
        use_root_disk: false
        size: 30720
  - name: large.ram
    cloud_properties:
      cpu: 4
      ram: 6144
      disk: 40960
  - name: large.disk
    cloud_properties:
      cpu: 4
      ram: 4096
      disk: 81920

compilation:
  reuse_compilation_vms: true
  az: azure-euw-dev
  network: azure-euw-dev-default
  vm_type: large
  workers: 3